<a href="https://colab.research.google.com/github/mohnishsachdeva/XOR-Problem/blob/main/xor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [ ]:

# define the input and output data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])


In [ ]:

# define the model architecture
model = Sequential()
model.add(Dense(3, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))



In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 3)                 9         
                                                                 
 dense_5 (Dense)             (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# train the model
model.fit(X, y, epochs=1000)



Epoch 1/1000
1/1 [==============================] - 1s 622ms/step - loss: 0.6236 - accuracy: 0.7500
Epoch 2/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6234 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.6231 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.6228 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6225 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6222 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6219 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6215 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.6212 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.6210 - accuracy: 0.5000
Epoch 11/10

In [ ]:
# evaluate the model
scores = model.evaluate(X, y)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

1/1 [==============================] - 0s 134ms/step - loss: 0.2212 - accuracy: 1.0000
accuracy: 100.0


In [ ]:
t = np.array([[1, 1], [0, 1], [1, 0], [0, 0]])

In [ ]:
y_pred = model.predict(t)

1/1 [==============================] - 0s 87ms/step


In [ ]:
y_pred

array([[0.17753284],
       [0.8215129 ],
       [0.8110688 ],
       [0.24685231]], dtype=float32)

In [ ]:
y_pred[0]

array([0.17753284], dtype=float32)

In [ ]:
len(y_pred)

4

In [ ]:
for i in range(len(y_pred)):
  print(i)

0
1
2
3


In [ ]:
assigned_value = np.array([])

In [ ]:
assigned_value.shape

(0,)

In [ ]:
for i in range(len(y_pred)):
  print(y_pred[i])
  if y_pred[i] > 0.5:
    assigned_value=np.append(assigned_value,1)
  else:
    assigned_value=np.append(assigned_value,0)

[0.17753284]
[0.8215129]
[0.8110688]
[0.24685231]


In [ ]:
assigned_value

array([0., 1., 1., 0.])